name: "Compress"
description: "Compress built files"
inputs:
  goos:
    description: "Target OS"
  goarch:
    description: "Target architecture"
runs:
  using: composite
  steps:
    - if: inputs.goos == 'linux'
      shell: bash
      run: |
        zip -r llm-language-server-${{ inputs.goos }}-${{ inputs.goarch }}.zip llm-language-server
    - if: inputs.goos == 'windows'
      shell: bash
      run: |
        zip -r llm-language-server-${{ inputs.goos }}-${{ inputs.goarch }}.zip llm-language-server.exe
    - if: inputs.goos == 'darwin'
      shell: bash
      run: |
        zip -r llm-language-server-${{ inputs.goos }}-${{ inputs.goarch }}.zip llm-language-server
