name: "Compress"
description: "Compress built files"
inputs:
  go-version:
    description: "Go version"
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      working-directory: build/bin
      run: |
        zip -r llm-language-server-linux.zip *
    - if: runner.os == 'Windows'
      shell: pwsh
      working-directory: build/bin
      run: |
        Compress-Archive -Path * -Destination llm-language-server-windows.zip
    - if: runner.os == 'macOs'
      shell: bash
      working-directory: build/bin
      run: |
        zip -r llm-language-server-macos.zip *
