name: "Compress"
description: "Compress built files"
inputs:
  goos:
    description: "Target OS"
runs:
  using: composite
  steps:
    - if: inputs.goos == 'linux'
      shell: bash
      run: |
        zip -r llm-language-server-linux.zip llm-language-server
    - if: inputs.goos == 'windows'
      shell: pwsh
      run: |
        Compress-Archive -Path llm-language-server.exe -Destination llm-language-server-windows.zip
    - if: inputs.goos == 'darwin'
      shell: bash
      run: |
        zip -r llm-language-server-macos.zip llm-language-server
