name: "Compress"
description: "Compress built files"
inputs:
  go-version:
    description: "Go version"
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        zip -r llm-language-server-linux.zip llm-language-server
    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Compress-Archive -Path llm-language-server.exe -Destination llm-language-server-windows.zip
    - if: runner.os == 'macOs'
      shell: bash
      run: |
        zip -r llm-language-server-macos.zip llm-language-server
