on:
  push:
    branches:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      goversion: ${{ steps.set-version.outputs.goversion }}
    steps:
      - id: set-version
        run: |
          echo "goversion=1.24.3" >> $GITHUB_OUTPUT
  setup:
    needs: [set-version]
    uses: ./.github/workflows/setup.yml
    with:
      goversion: ${{ needs.set-version.outputs.goversion }}
  build:
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    runs-on: ubuntu-latest
    needs: [set-version, setup]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          goversion: ${{ needs.set-version.outputs.goversion }}
  test:
    runs-on: ubuntu-latest
    needs: [set-version, build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          goversion: ${{ needs.set-version.outputs.goversion }}
      - shell: bash
        run: go test ./...
