on:
  release:
    types: [published]
jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.set-version.outputs.go-version }}
    steps:
      - id: set-version
        run: |
          echo "go-version=1.24.3" >> $GITHUB_OUTPUT
  setup:
    needs: [set-version]
    uses: ./.github/workflows/setup.yml
    with:
      go-version: ${{ needs.set-version.outputs.go-version }}
  build:
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [386, amd64, arm, arm64]
    runs-on: ubuntu-latest
    needs: [set-version, setup]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          go-version: ${{ needs.set-version.outputs.go-version }}
          go-os: ${{ matrix.os }}
          go-arch: ${{ maxtrix.arch }}
      - uses: ./.github/actions/zip
        with:
          go-os: ${{ matrix.os }}
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
