on:
  release:
    types: [published]
jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      goversion: ${{ steps.set-version.outputs.goversion }}
    steps:
      - id: set-version
        run: |
          echo "goversion=1.24.3" >> $GITHUB_OUTPUT
  setup:
    needs: [set-version]
    uses: ./.github/workflows/setup.yml
    with:
      goversion: ${{ needs.set-version.outputs.goversion }}
  build:
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
    runs-on: ubuntu-latest
    needs: [set-version, setup]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          goversion: ${{ needs.set-version.outputs.goversion }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
      - uses: ./.github/actions/zip
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
